# coding: utf-8

"""
    API whatsgate.ru

    Интерфейс для взаимодействия с клиентом Whatsapp  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.response_chat_group_metadata import ResponseChatGroupMetadata  # noqa: E501
from swagger_client.rest import ApiException


class TestResponseChatGroupMetadata(unittest.TestCase):
    """ResponseChatGroupMetadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testResponseChatGroupMetadata(self):
        """Test ResponseChatGroupMetadata"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.response_chat_group_metadata.ResponseChatGroupMetadata()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
