# coding: utf-8

"""
    API whatsgate.ru

    Интерфейс для взаимодействия с клиентом Whatsapp  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.any_ofsend_body_message import AnyOfsendBodyMessage  # noqa: E501
from swagger_client.rest import ApiException


class TestAnyOfsendBodyMessage(unittest.TestCase):
    """AnyOfsendBodyMessage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAnyOfsendBodyMessage(self):
        """Test AnyOfsendBodyMessage"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.any_ofsend_body_message.AnyOfsendBodyMessage()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
