# coding: utf-8

"""
    API whatsgate.ru

    Интерфейс для взаимодействия с клиентом Whatsapp  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_check_post(self):
        """Test case for check_post

        Проверка зарегистрирован ли номер в WhatsApp  # noqa: E501
        """
        pass

    def test_get_chats_post(self):
        """Test case for get_chats_post

        Возвращает список активных чатов  # noqa: E501
        """
        pass

    def test_seen_post(self):
        """Test case for seen_post

        Отправляет команду в чат, что последние сообщения просмотрены  # noqa: E501
        """
        pass

    def test_send_message(self):
        """Test case for send_message

        Отправка сообщения  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
