# coding: utf-8

"""
    API whatsgate.ru

    Интерфейс для взаимодействия с клиентом Whatsapp  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.__api import _Api  # noqa: E501
from swagger_client.rest import ApiException


class Test_Api(unittest.TestCase):
    """_Api unit test stubs"""

    def setUp(self):
        self.api = _Api()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_media_post(self):
        """Test case for get_media_post

        Возвращает объект медиафайла, прикрепленного к сообщению  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
