# coding: utf-8

"""
    API whatsgate.ru

    Интерфейс для взаимодействия с клиентом Whatsapp  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.media import Media  # noqa: E501
from swagger_client.rest import ApiException


class TestMedia(unittest.TestCase):
    """Media unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMedia(self):
        """Test Media"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.media.Media()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
