# coding: utf-8

# flake8: noqa
"""
    API whatsgate.ru

    Интерфейс для взаимодействия с клиентом Whatsapp  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.any_ofseen_body_recipient import AnyOfseenBodyRecipient
from swagger_client.models.any_ofsend_body_message import AnyOfsendBodyMessage
from swagger_client.models.any_ofsend_body_recipient import AnyOfsendBodyRecipient
from swagger_client.models.check_body import CheckBody
from swagger_client.models.error import Error
from swagger_client.models.getchats_body import GetchatsBody
from swagger_client.models.getmedia_body import GetmediaBody
from swagger_client.models.inline_response200 import InlineResponse200
from swagger_client.models.inline_response2001 import InlineResponse2001
from swagger_client.models.inline_response2002 import InlineResponse2002
from swagger_client.models.inline_response2003 import InlineResponse2003
from swagger_client.models.inline_response2004 import InlineResponse2004
from swagger_client.models.media import Media
from swagger_client.models.message_media import MessageMedia
from swagger_client.models.message_text import MessageText
from swagger_client.models.one_ofinline_response200_result import OneOfinlineResponse200Result
from swagger_client.models.recipient_id import RecipientId
from swagger_client.models.recipient_num import RecipientNum
from swagger_client.models.response_async import ResponseAsync
from swagger_client.models.response_chat import ResponseChat
from swagger_client.models.response_chat_group_metadata import ResponseChatGroupMetadata
from swagger_client.models.response_chat_group_metadata_participants import ResponseChatGroupMetadataParticipants
from swagger_client.models.response_message import ResponseMessage
from swagger_client.models.seen_body import SeenBody
from swagger_client.models.send_body import SendBody
