# coding: utf-8

"""
    API whatsgate.ru

    Интерфейс для взаимодействия с клиентом Whatsapp  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MessageMedia(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'body': 'str',
        'quote': 'str',
        'type': 'str',
        'media': 'Media'
    }

    attribute_map = {
        'body': 'body',
        'quote': 'quote',
        'type': 'type',
        'media': 'media'
    }

    def __init__(self, body=None, quote=None, type=None, media=None):  # noqa: E501
        """MessageMedia - a model defined in Swagger"""  # noqa: E501
        self._body = None
        self._quote = None
        self._type = None
        self._media = None
        self.discriminator = None
        if body is not None:
            self.body = body
        if quote is not None:
            self.quote = quote
        if type is not None:
            self.type = type
        if media is not None:
            self.media = media

    @property
    def body(self):
        """Gets the body of this MessageMedia.  # noqa: E501


        :return: The body of this MessageMedia.  # noqa: E501
        :rtype: str
        """
        return self._body

    @body.setter
    def body(self, body):
        """Sets the body of this MessageMedia.


        :param body: The body of this MessageMedia.  # noqa: E501
        :type: str
        """

        self._body = body

    @property
    def quote(self):
        """Gets the quote of this MessageMedia.  # noqa: E501


        :return: The quote of this MessageMedia.  # noqa: E501
        :rtype: str
        """
        return self._quote

    @quote.setter
    def quote(self, quote):
        """Sets the quote of this MessageMedia.


        :param quote: The quote of this MessageMedia.  # noqa: E501
        :type: str
        """

        self._quote = quote

    @property
    def type(self):
        """Gets the type of this MessageMedia.  # noqa: E501


        :return: The type of this MessageMedia.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this MessageMedia.


        :param type: The type of this MessageMedia.  # noqa: E501
        :type: str
        """
        allowed_values = ["image", "sticker", "doc", "voice"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"  # noqa: E501
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def media(self):
        """Gets the media of this MessageMedia.  # noqa: E501


        :return: The media of this MessageMedia.  # noqa: E501
        :rtype: Media
        """
        return self._media

    @media.setter
    def media(self, media):
        """Sets the media of this MessageMedia.


        :param media: The media of this MessageMedia.  # noqa: E501
        :type: Media
        """

        self._media = media

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MessageMedia, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MessageMedia):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
