# coding: utf-8

"""
    API whatsgate.ru

    Интерфейс для взаимодействия с клиентом Whatsapp  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SendBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'whatsapp_id': 'str',
        '_async': 'bool',
        'recipient': 'AnyOfsendBodyRecipient',
        'message': 'AnyOfsendBodyMessage'
    }

    attribute_map = {
        'whatsapp_id': 'WhatsappID',
        '_async': 'async',
        'recipient': 'recipient',
        'message': 'message'
    }

    def __init__(self, whatsapp_id=None, _async=None, recipient=None, message=None):  # noqa: E501
        """SendBody - a model defined in Swagger"""  # noqa: E501
        self._whatsapp_id = None
        self.__async = None
        self._recipient = None
        self._message = None
        self.discriminator = None
        self.whatsapp_id = whatsapp_id
        if _async is not None:
            self._async = _async
        if recipient is not None:
            self.recipient = recipient
        if message is not None:
            self.message = message

    @property
    def whatsapp_id(self):
        """Gets the whatsapp_id of this SendBody.  # noqa: E501

        Service Whatsapp ID  # noqa: E501

        :return: The whatsapp_id of this SendBody.  # noqa: E501
        :rtype: str
        """
        return self._whatsapp_id

    @whatsapp_id.setter
    def whatsapp_id(self, whatsapp_id):
        """Sets the whatsapp_id of this SendBody.

        Service Whatsapp ID  # noqa: E501

        :param whatsapp_id: The whatsapp_id of this SendBody.  # noqa: E501
        :type: str
        """
        if whatsapp_id is None:
            raise ValueError("Invalid value for `whatsapp_id`, must not be `None`")  # noqa: E501

        self._whatsapp_id = whatsapp_id

    @property
    def _async(self):
        """Gets the _async of this SendBody.  # noqa: E501

        Async query returns Message Object  # noqa: E501

        :return: The _async of this SendBody.  # noqa: E501
        :rtype: bool
        """
        return self.__async

    @_async.setter
    def _async(self, _async):
        """Sets the _async of this SendBody.

        Async query returns Message Object  # noqa: E501

        :param _async: The _async of this SendBody.  # noqa: E501
        :type: bool
        """

        self.__async = _async

    @property
    def recipient(self):
        """Gets the recipient of this SendBody.  # noqa: E501


        :return: The recipient of this SendBody.  # noqa: E501
        :rtype: AnyOfsendBodyRecipient
        """
        return self._recipient

    @recipient.setter
    def recipient(self, recipient):
        """Sets the recipient of this SendBody.


        :param recipient: The recipient of this SendBody.  # noqa: E501
        :type: AnyOfsendBodyRecipient
        """

        self._recipient = recipient

    @property
    def message(self):
        """Gets the message of this SendBody.  # noqa: E501


        :return: The message of this SendBody.  # noqa: E501
        :rtype: AnyOfsendBodyMessage
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this SendBody.


        :param message: The message of this SendBody.  # noqa: E501
        :type: AnyOfsendBodyMessage
        """

        self._message = message

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SendBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SendBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
